language: cpp
compiler:
  - clang

before_install:
 - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
 - sudo apt-get update -qq
 - sudo apt-get install cmake
 - sudo apt-get install libzmq3-dev
 - sudo apt-get install -qq libboost-dev

script: mkdir build && cd build && cmake ../ && make
